# -*- coding: utf-8 -*-
"""OasisTask5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V_5mO0MbUDVWh6Fjpzjt08Tp1YsKO7i

# Sales Prediction Using Machine Learning

This project predicts product sales based on advertising spending on
TV, Radio, and Newspaper platforms.

Using machine learning techniques, we analyze the relationship between
advertising budgets and sales to build a predictive model.

Algorithm Used: Linear Regression
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("Advertising.csv")

df.head()

print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns)

df.info()

df.describe()

df = df.drop(columns=['Unnamed: 0'], errors='ignore')

df.isnull().sum()

sns.pairplot(df)
plt.show()

plt.figure(figsize=(6,4))

sns.heatmap(df.corr(), annot=True, cmap="coolwarm")

plt.title("Correlation Between Advertising Channels and Sales")

plt.show()

X = df[['TV','Radio','Newspaper']]
y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

plt.figure(figsize=(6,4))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")

plt.title("Actual vs Predicted Sales")

plt.show()

sample = [[150, 25, 20]]

prediction = model.predict(sample)

print("Predicted Sales:", prediction)

"""## Conclusion

In this project, a machine learning model was built to predict product sales
based on advertising expenditures.

Using Linear Regression, we analyzed how advertising channels such as TV,
Radio, and Newspaper influence product sales.

The model achieved good prediction performance, demonstrating that
advertising spending plays a significant role in driving sales.
"""